spring:
  application:
    name: Tlias-web-demo
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Tlias_db
    username: root

mybatis:
  configuration:
    # mysql数据库映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰映射
    map-underscore-to-camel-case: true